apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: determine-path
  namespace: lmw-fitness
spec:
  params:
    - name: SERVICE_TYPE
      type: string
      description: "The type of service"
  steps:
    - name: determine-path
      image: alpine
      script: |
        #!/bin/sh
        if [ "$(params.SERVICE_TYPE)" = "backend" ]; then
          echo ".api.image.repository" > /workspace/path
        else
          echo ".webserver.image.repository" > /workspace/path
        fi
  results:
    - name: IMAGE_PATH
      description: "The determined path for the image"
      value: $(cat /workspace/path) 