apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-image
  namespace: lmw-fitness
spec:
  params:
    - name: VALUES_MANIFEST_PATH
      type: string
      description: Path to the helm values to change image name
    - name: VALUES_PATH_TO_IMAGE
      type: string
      description: The path to the image to replace in the yaml manifest (arg to yq)
    - name: NEXUS_IMAGE 
      type: string
      description: The name of the image that was built 
  steps:
    - name: update-image
      image: mikefarah/yq
      workingDir: $(workspaces.helm-chart.path)
      script: |
        yq -i '$(params.VALUES_PATH_TO_IMAGE) = "$(params.NEXUS_IMAGE)"' $(params.VALUES_MANIFEST_PATH)
  workspaces:
    - name: helm-chart
  results:
    - name: IMAGE 
      description: The name of the image that was built