apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener
  namespace: lmw-fitness
spec:
  serviceAccountName: default
  triggers:
    - name: trigger
      bindings:
        - ref: trigger-binding
      interceptors:
        - ref:
            name: github
          params:
            - name: secretRef
              value:
                secretName: github-secret
                secretKey: secret
            - name: eventTypes
              value: ["push"]
            - name: addChangedFiles
              value: ["true"]
            - name: githubOrg
              value: ["laurawarren88"]
            - name: githubRepo
              value: ["backend-go-fitness-locator"]
            - name: debug
              value: "true"
      template:
        ref: trigger-template
