apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
  namespace: lmw-fitness
spec:
  params:
    - name: GITHUB_CLONE_URL
      value: $(body.repository.clone_url)
    - name: GITHUB_HELM_URL
      value: "https://github.com/laurawarren88/helm-chart.git"
    - name: SONAR_HOST_URL
      value: "http://sonarqube-sonarqube.lmw-fitness.svc.cluster.local:9000"
    - name: PROJECT_KEY
      value: "fitness-locator"
    - name: DOCKER_IMAGE
      value: "docker.io/lmwcode/$(body.repository.name):$(body.after)"
    - name: NEXUS_IMAGE
      value: "lmw.nexus.hyades.clusters.easlab.co.uk/$(body.repository.name):$(body.after)"
    - name: DOCKERFILE
      value: Dockerfile
    - name: CONTEXT
      value: "."
    - name: BUILDER_IMAGE
      value: "gcr.io/kaniko-project/executor:v1.5.1@sha256:c6166717f7fe0b7da44908c986137ecfeab21f31ec3992f6e128fff8a94be8a5"
    - name: TRIVY_SEVERITY
      value: "CRITICAL,HIGH"
    - name: VALUES_MANIFEST_PATH
      value: "values.yaml"
    - name: SERVICE_TYPE
      value: $(body.repository.description)
    - name: GITHUB_EMAIL
      value: laura@enterpriseautomation.co.uk
    - name: GITHUB_USERNAME
      value: laurawarren88
    - name: HELM_FILE
      value: "helm-chart/"
    - name: COMMIT_MESSAGE
      value: "Update image in Helm chart"

    
      