apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: nexus-ui
    port: {{ .Values.Nexus.uiPort }}
    targetPort: {{ .Values.Nexus.uiPort }}
  - name: nexus-docker
    port: {{ .Values.Nexus.dockerPort }}
    targetPort: {{ .Values.Nexus.dockerPort }}
  selector:
    app: nexus