apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  labels:
    name: nexus-pv 
spec:
  storageClassName: {{ .Values.Nexus.storageClass }}
  capacity:
    storage: {{ .Values.Nexus.storageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: {{ .Values.namespace }}
spec:
  volumeName: nexus-pv
  storageClassName: {{ .Values.Nexus.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.Nexus.storageSize }}